### ISSUE TITLE
Bug:order fails with ethers client

### ISSUE THREAD

**Issue by jestersimpps** [nktkas/hyperliquid#1]
order fails

Briefly describe the bug.

order {
  a: 150,
  b: false,
  p: '25.20',
  s: '0.2',
  r: false,
  t: { limit: { tif: 'Gtc' } }
}

Provide a minimal code snippet that reproduces the bug.

order success

Explain what should happen vs. what actually happens.

{
  "name": "ApiRequestError",
  "stack": "ApiRequestError: L1 error: User or API Wallet 0x5edc985e39493f019bf20f5a800c900b03cdaa3a does not exist.\n    at WalletClient.validateResponse (file:///Users/jovinkenroye/Sites/triggers/node_modules/@nktkas/hyperliquid/src/clients/wallet.ts:1161:19)\n    at WalletClient.order (file:///Users/jovinkenroye/Sites/triggers/node_modules/@nktkas/hyperliquid/src/clients/wallet.ts:627:14)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at run (file:///Users/jovinkenroye/Sites/triggers/src/trigger/trading-broker.ts:237:21)\n    at file:///Users/jovinkenroye/.npm/_npx/f51a09bd0abf5f10/node_modules/@trigger.dev/core/src/v3/workers/taskExecutor.ts:125:28\n    at ConsoleInterceptor.intercept (file:///Users/jovinkenroye/.npm/_npx/f51a09bd0abf5f10/node_modules/@trigger.dev/core/src/v3/consoleInterceptor.ts:36:14)\n    at result._tracer.startActiveSpan.kind (file:///Users/jovinkenroye/.npm/_npx/f51a09bd0abf5f10/node_modules/@trigger.dev/core/src/v3/workers/taskExecutor.ts:89:16)\n    at file:///Users/jovin",
  "message": "L1 error: User or API Wallet 0x5edc985e39493f019bf20f5a800c900b03cdaa3a does not exist."
}

Paste relevant error messages or logs here.

**Environment**

- `@nktkas/hyperliquid` version:
- Runtime environment (Node.js/Deno/Bun) and its version:
- Operating System:

**Additional Context (optional)**

Include any other relevant information.

**Comment by jestersimpps** [comment]
same with viem wallet :/

**Comment by nktkas** [comment]
HyperLiquid doesn't like the 0 at the end of the price. Without it there is no error "L1 error ..."

```ts
import { HttpTransport, WalletClient } from "@nktkas/hyperliquid";
import { privateKeyToAccount } from "viem/accounts";

const account = privateKeyToAccount("0x...");
const transport = new HttpTransport({ url: "https://api.hyperliquid-testnet.xyz" });
const walletClient = new WalletClient(account, transport, true);

// Error code
const res = await walletClient.order({
    orders: [{
        a: 150,
        b: false,
        p: "25.20", // HyperLiquid doesn't like the 0 at the end
        s: "0.2",
        r: false,
        t: { limit: { tif: "Gtc" } },
    }],
    grouping: "na",
});
// Response:
// {
//   status: "err",
//   response: "L1 error: User or API Wallet 0x882197e2db292b7423970075355a40a6d86422ca does not exist.",
// }

// Valid code
const res = await walletClient.order({
    orders: [{
        a: 150,
        b: false,
        p: "25.2", // Now it's right
        s: "0.2",
        r: false,
        t: { limit: { tif: "Gtc" } },
    }],
    grouping: "na",
});
// Response:
// {
//   status: "ok",
//   response: {
//     type: "order",
//     data: {
//       statuses: [{ error: "Asset 150 is out of range." }], // See: https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/asset-ids
//     },
//   },
// }
```

**Comment by jestersimpps** [comment]
thank you for your quick response.
i fixed the size and price strings, however, i am still struggling with the signature:

{
  "name": "ApiRequestError",
  "stack": "ApiRequestError: L1 error: User or API Wallet 0x5780a7e262dfff4ae7a40042600a70c486d1bbc4 does not exist.\n    at WalletClient.validateResponse (file:///Users/jovinkenroye/Sites/triggers/node_modules/@nktkas/hyperliquid/src/clients/wallet.ts:1161:19)\n    at WalletClient.order (file:///Users/jovinkenroye/Sites/triggers/node_modules/@nktkas/hyperliquid/src/clients/wallet.ts:627:14)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at run (file:///Users/jovinkenroye/Sites/triggers/src/trigger/trading-broker.ts:237:21)\n    at file:///Users/jovinkenroye/.npm/_npx/f51a09bd0abf5f10/node_modules/@trigger.dev/core/src/v3/workers/taskExecutor.ts:125:28\n    at ConsoleInterceptor.intercept (file:///Users/jovinkenroye/.npm/_npx/f51a09bd0abf5f10/node_modules/@trigger.dev/core/src/v3/consoleInterceptor.ts:36:14)\n    at result._tracer.startActiveSpan.kind (file:///Users/jovinkenroye/.npm/_npx/f51a09bd0abf5f10/node_modules/@trigger.dev/core/src/v3/workers/taskExecutor.ts:89:16)\n    at file:///Users/jovin",
  "message": "L1 error: User or API Wallet 0x5780a7e262dfff4ae7a40042600a70c486d1bbc4 does not exist."
}

**Comment by nktkas** [comment]
Please provide minimum reproducible code.

**Comment by jestersimpps** [comment]
i have figured it out. I am using some of the methods you used in the testing Util library. it would be nice if we could export some of these utility functions.

```typescript
import {
 Order,
 OrderResponseSuccess,
 CancelResponseSuccess,
 TIF,
} from "@nktkas/hyperliquid";
import { HyperliquidExchangeAPI } from "../hyperliquid-api/exchange";
import { getAssetData, getPxDecimals } from "../util/conversions";
import BigNumber from "bignumber.js";

export interface ToolOrder {
 symbol: string;
 isBuy: boolean;
 price: string;
 size: string;
 isReduceOnly: boolean;
 orderType:
  | {
     /** Limit order parameters. */
     limit: {
      /** Time-in-force. */
      tif: TIF;
     };
    }
  | {
     /** Trigger order parameters. */
     trigger: {
      /** Is the market order. */
      isMarket: boolean;

      /** Trigger price. */
      triggerPx: string;

      /** Indicates if it's take-profit or stop-loss. */
      tpsl: "tp" | "sl";
     };
    };
}

export interface ToolCancel {
 symbol: string;
 orderId: number;
}

export class TradingTools {
 private api: HyperliquidExchangeAPI;
 private marketData;

 constructor() {
  this.api = new HyperliquidExchangeAPI();
  this.getMArketData();
 }

 async getMArketData() {
  this.marketData = await this.api.client.metaAndAssetCtxs();
 }

 async placeOrder(order: ToolOrder): Promise<OrderResponseSuccess | string> {
  const { id, universe, ctx } = await getAssetData(
   this.marketData,
   order.symbol
  );
  const pxDecimals = getPxDecimals("perp", universe.szDecimals);
  const px = new BigNumber(order.price)
   .decimalPlaces(pxDecimals, BigNumber.ROUND_DOWN)
   .toString();
  const sz = new BigNumber(order.size)
   .decimalPlaces(universe.szDecimals, BigNumber.ROUND_DOWN)
   .toString();

  const result = await this.api.walletClient.order({
   orders: [
    {
     a: id,
     b: order.isBuy,
     p: px,
     s: sz,
     r: order.isReduceOnly,
     t: order.orderType,
    },
   ],
   grouping: "na",
  });

  const [orderResponse] = result.response.data.statuses;
  console.log("order", orderResponse);

  return result;
 }

 async cancelOrders(cancels: ToolCancel[]): Promise<CancelResponseSuccess[]> {
  const results: CancelResponseSuccess[] = [];
  for (let cancel of cancels) {
   const { id, universe, ctx } = await getAssetData(
    this.marketData,
    cancel.symbol
   );
   results.push(
    await this.api.walletClient.cancel({
     cancels: [{ a: id, o: cancel.orderId }],
    })
   );
  }

  console.log("cancels", results);
  // return "ok";
  return results;
 }
}
```

**Comment by jestersimpps** [comment]
it's not your code, but these are some cryptic error messages... was expecting faulty singing method.
