### ISSUE TITLE
Bug: `order()` should also accept an array of Cloid's

### ISSUE THREAD

**Issue by defidefi5** [nktkas/hyperliquid#3]
**Bug Description**

If you send multiple orders at once like this

```ts
const result = await client.order({
  orders: [
    {
      // spot PURR
      a: 10_000,
      b: true,
      p: "0.2",
      s: "100",
      r: false,
      t: { limit: { tif: "Alo" } }
    },
    {
      // spot HYPE
      a: 10_107,
      b: true,
      p: "10",
      s: "1",
      r: false,
      t: { limit: { tif: "Alo" }
    },

    c: randomCloid()
    // c: [randomCloid(), randomCloid()] // not possible
  }],
  grouping: "na" 
});
```

you will get a response like e

```json
{
  "status": "ok",
  "response": {
    "type": "order",
    "data": {
      "statuses": [
        {
          "resting": {
            "oid": 12345677
          }
        },
        {
          "resting": {
            "oid": 12345678,
            "cloid": "0x..."
          }
        }
      ]
    }
  }
}
```

**Expected vs. Actual Behavior**

**Expected:**
Both orders should have a unique `cloid` property. 

**Actual:**
Only one order has a client order ID

**Suggested solution**

Allow order property of 'c' to be either a `string` or `string[]`. 

Don't throw an error in any situation related to the array of client OIDs: if the array is too short, just don't use a client OID; if it's too long, then the extraneous COIDs simply remain unused.

**Environment**

- `@nktkas/hyperliquid` version: 0.11.1

**Comment by defidefi5** [comment]
Also, really great work on this lib! The consistency throughout of comments, etc is so good, I'm inclined to ask if you used a certain `.cursorrules` file that works well or certain model for code generation. I can see a lot of attention to detail.

**Comment by nktkas** [comment]
> **Bug Description**
> 
> If you send multiple orders at once like this
> 
> ```ts
> const result = await client.order({
>   orders: [
>     {
>       // spot PURR
>       a: 10_000,
>       b: true,
>       p: "0.2",
>       s: "100",
>       r: false,
>       t: { limit: { tif: "Alo" } }
>     },
>     {
>       // spot HYPE
>       a: 10_107,
>       b: true,
>       p: "10",
>       s: "1",
>       r: false,
>       t: { limit: { tif: "Alo" }
>     },
> 
>     c: randomCloid()
>     // c: [randomCloid(), randomCloid()] // not possible
>   }],
>   grouping: "na" 
> });
> ```
> 
> you will get a response like e
> 
> ```json
> {
>   "status": "ok",
>   "response": {
>     "type": "order",
>     "data": {
>       "statuses": [
>         {
>           "resting": {
>             "oid": 12345677
>           }
>         },
>         {
>           "resting": {
>             "oid": 12345678,
>             "cloid": "0x..."
>           }
>         }
>       ]
>     }
>   }
> }
> ```
> 
> **Expected vs. Actual Behavior**
> 
> **Expected:** Both orders should have a unique `cloid` property.
> 
> **Actual:** Only one order has a client order ID
> 
> **Suggested solution**
> 
> Allow order property of 'c' to be either a `string` or `string[]`.
> 
> Don't throw an error in any situation related to the array of client OIDs: if the array is too short, just don't use a client OID; if it's too long, then the extraneous COIDs simply remain unused.
> 
> **Environment**
> 
> * `@nktkas/hyperliquid` version: 0.11.1

You're using "c" incorrectly. It is specified together with the order object.

Example:
```ts
import { type Hex, HttpTransport, WalletClient } from "@nktkas/hyperliquid";
import { privateKeyToAccount } from "viem/accounts";

/**
 * Generate a random Client Order ID
 * @returns Client Order ID
 */
function randomCloid(): Hex {
    return `0x${Array.from({ length: 32 }, () => Math.floor(Math.random() * 16).toString(16)).join("")}`;
}

const account = privateKeyToAccount("0x..."); // your private key
const transport = new HttpTransport({ url: "https://api.hyperliquid-testnet.xyz" });
const walletClient = new WalletClient(account, transport, true);

const result = await walletClient.order({
    orders: [
        {
            // spot PURR
            a: 10_000,
            b: true,
            p: "0.2",
            s: "100",
            r: false,
            t: { limit: { tif: "Alo" } },
            c: randomCloid(),
        },
        {
            // spot HYPE
            a: 10_107,
            b: true,
            p: "100",
            s: "1",
            r: false,
            t: { limit: { tif: "Alo" } },
            c: randomCloid(),
        },
    ],
    grouping: "na",
});
// result:
// {
//   status: "ok",
//   response: {
//     type: "order",
//     data: {
//       statuses: [
//         {
//           resting: {
//             oid: 21483577128,
//             cloid: "0x9078cd7ef8965dcb9833b2bc04957a49",
//           },
//         },
//         {
//           resting: {
//             oid: 21483577129,
//             cloid: "0x80f9d926c1ffc8bc239ce1c14cd2316f",
//           },
//         },
//       ],
//     },
//   },
// }

```

Update: Your problem is due to broken brackets:
![image](https://github.com/user-attachments/assets/9bd0078b-f97b-4b89-b723-913b31241434)

**Comment by nktkas** [comment]
> Also, really great work on this lib! The consistency throughout of comments, etc is so good, I'm inclined to ask if you used a certain `.cursorrules` file that works well or certain model for code generation. I can see a lot of attention to detail.

I've been using Github Copilot as a helper to autocomplete code (full-fledged functions it doesn't generate the way I like), and Claude to bring all my comments in types to a consistent style.

**Comment by defidefi5** [comment]
Oh! That makes more sense. Thanks for catching that...funny that it still kinda worked! haha

I've looked through the code to offer suggestions, but so far everything I've seen has been great!
