### ISSUE TITLE
Feature: Add `close()` method to PublicClient and WalletClient that invokes `close()` on the WebSocket transport.

### ISSUE THREAD

**Issue by defidefi5** [nktkas/hyperliquid#7]
**Description of the Desired Feature**

Assuming I use a Websocket transport, I'd like to be able to invoke a close method on the clients directly, 

<img width="800" alt="x" src="https://github.com/user-attachments/assets/bb684027-0f84-4916-907c-9aa1ca6330a6" />

**Motivation and Use Case**

This would allow me to have cleaner code because I wouldn't need to add both the client (to call its methods however needed) and the transport (for the single purpose of being able to invoke the `close()` method on app shutdown), to my class. It would allow for a cleaner dev experience and keep my Class prototype more minimal.

**Proposed Solution**

Add a `close()` method to PublicClient and WalletClient. It if the `close()` method exists on the transport and invokes it if it does, (b/c close will not exist on the REST transport).

**Comment by nktkas** [comment]
Context: This is a low-level SDK, it should be simple and logically straightforward.

Adding “close” to PublicClient/WalletClient violates the SRP principle and Increased Coupling with transport for the sake of syntactic sugar.
I think this is a bad idea.

If you need “close” in PublicClient/WalletClient, I can suggest extending the source classes/types:
```ts
import { type IRESTTransport, PublicClient, WebSocketTransport } from "@nktkas/hyperliquid";

interface ExtendsIRESTTransport extends IRESTTransport {
    close?(): void | Promise<void>;
}

class ExtendsPublicClient extends PublicClient {
    constructor(public override transport: ExtendsIRESTTransport) {
        super(transport);
    }

    async close(): Promise<void> {
        return await this.transport.close?.();
    }
}

// Example usage
const transport = new WebSocketTransport();
const client = new ExtendsPublicClient(transport);
await client.close();

// Alternative version without modification of interfaces
const transport = new WebSocketTransport();
const client = new PublicClient(transport);
if ("close" in client.transport && typeof client.transport.close === "function") {
    await client.transport.close();
}
```

**Comment by nktkas** [comment]
> If you need “close” in PublicClient/WalletClient, I can suggest extending the source classes/types:

I came up with a more elegant solution. I can add Generics to PublicClient/WalletClient. This is a better solution than any of the options above. It should also solve your problem, provided you are using TypeScript.

**Comment by nktkas** [comment]
Implemented in https://github.com/nktkas/hyperliquid/commit/4ad416d3c207e7dc98e2a288621a51ccb7fc81ae.

Now you can use features of passed transport via PublicClient/WalletClient:
```ts
import { HttpTransport, PublicClient, WebSocketTransport } from "@nktkas/hyperliquid";

// Example 1:
const transport = new WebSocketTransport();
const client = new PublicClient({ transport }); // PublicClient<WebSocketTransport>
await client.transport.close(); // No type error

// Example 2:
const transport = new HttpTransport();
const client = new PublicClient({ transport }); // PublicClient<HttpTransport>
await client.transport.close(); // TSError: Property 'close' does not exist on type 'HttpTransport'.
```

**Comment by defidefi5** [comment]
Neat. Thanks! I'll watch for the new release.

**Comment by defidefi5** [comment]
@nktkas I tried v`0.12.0`  and `0.13.0-beta.1` and get this lint error:

<img width="989" alt="Screenshot" src="https://github.com/user-attachments/assets/b94409d2-bc88-47d8-9fac-722dd59ac36b" />

Did only the docs for this get pushed by chance? Maybe the implementation still needs to be committed

**Comment by nktkas** [comment]
> @nktkas I tried v`0.12.0` and `0.13.0-beta.1` and get this lint error:
> 
> <img alt="Screenshot" width="989" src="https://private-user-images.githubusercontent.com/192141790/401295631-b94409d2-bc88-47d8-9fac-722dd59ac36b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0Mjk1MTAsIm5iZiI6MTczNjQyOTIxMCwicGF0aCI6Ii8xOTIxNDE3OTAvNDAxMjk1NjMxLWI5NDQwOWQyLWJjODgtNDdkOC05ZmFjLTcyMmRkNTlhYzM2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOVQxMzI2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjI0MDY3NGZjY2Q3ZjliMTIzYzdmN2ZhMTlhZmFhNDBlZDY0ODY5ZTc0ZjVmMmExMDNhYTlmZWYwZjBjMjg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iRtonjo5HqVNlPne9W3O_jVbMY8e9DcLfgkfxIvUXlY">
> Did only the docs for this get pushed by chance? Maybe the implementation still needs to be committed

Provide additional information about the environment and reproducible code.

**Comment by defidefi5** [comment]
@nktkas I just solved it. When using `0.12.0`, updating the type of my property on my application's class from `hl.PublicClient` to `hl.PublicClient<hl.WebSocketTransport>` solved it. Thanks though
